[build]
    functions = "functions"

[[redirects]]
  from = '/*'
  to = 'https://reveal-server.netlify.app/.netlify/functions/server'
  force = true
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
